# Generated by Django 4.2 on 2025-04-27 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('no_of_dependents', models.IntegerField()),
                ('education', models.CharField(choices=[('graduate', 'Graduate'), ('not_graduate', 'Not Graduate')], max_length=20)),
                ('self_employed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('income_annum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_term', models.IntegerField(help_text='Term in years')),
                ('cibil_score', models.IntegerField()),
                ('residential_assets_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commercial_assets_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('luxury_assets_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_asset_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
